// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elajfjgnnlnpkxmvxvqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYWpmamdubmxucGt4bXZ4dnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDQ2NDIsImV4cCI6MjA3MDI4MDY0Mn0.SvTRKcSh5Tj6Mg8-6trk5hluJpo4m2x4AzYgX6lggMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});